language: ruby
rvm:
- 2.2.5
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
deploy:
  provider: s3
  local_dir: _site
  access_key_id:
    secure: c36ox+n4DkrBKKSJMspx9Pp7vgLj0zsPzWt/c28ZnWSuvN+ZEcu2uw3k4++vdi9clFP3/Ur6X6oQlv/qC/02Ig4iMO+ULcSpwBxAdQUKgJavGEFOY2v4/rlGiFoPnDxrwhtZgCGVm7gtwmoF2pomkFKJkuR+EujYSxc5DidZ7jD6O5VpLugDaSDZ3TwHEB8lMb58fTYkRAVyJ8/3MVVX9VZWIFVD7NebkAOuYwLrHRT0CO4AmZMjkKyMGBUMmbgcQUInlC2DUooGdDjQzs11FHJYnGvgrGzU4vATRQb8wdo6qCIVEciVwTvXB/r75DQ7mkdFj0I7wK+IquHYP4HY0dIHljfQO0VGAeeKxgg7iaLBGlKh+JzxL9z9DiDKPrEcLQs+yy9hQv93AKc0UPRn8T1X5xMSgu31I8sqSFyrmv8vnkPCK3+veu2LtDUFzc7uNVB2BPdm6gH/8FWzTmNFaH4B7X4fKnHNjpslyg2P/+xPF0vB4qGrFZ9Yd6TQUOmzyRngKCVNuxpVyAIICd5REfeGnobL607xObByuujpbHgT7DfymXoUdRGRC3W70Bnn6J1UbFk/l4Y51XDKbDgFYwijX/BWopdOMVptlZSnhQLyvMMMqu4FxZqKelZ68ZM8v3F4/ZdgE+iCDGZYNgafsP6zaEmqttmheBoDxba1FNk=
  secret_access_key:
    secure: gOkH5oo301MCF8QFPhWKijyyV++TnOOcvE3nKtrGDJpdTvR9IHcuhVyzBx4P87KzNeEIuxklyrYNZYVnfKG2KakZiHciiMZuZj3ufqFF51tbjaxJ3Mr8QAxR3+va450RZPuOqAL9Tswqbiw/Ypd6pZxxyGd1ZTfPzNmEzJKPrjwjPp9CKPrW1J6tCS+J1dOgo0RwhBDhpfRIpKHL/GAa4l7Xr8wv/QN2U785xylIxRFu5734HETzxvjKWhfvBnkqXtIhUD1hLjYynSDJSXoi17vgDA9gS+Qjvz3VQ2lPs+C5rLYfhqT9/NiuFO+yI6u/xqu0+9TRO93odC9Qy/kxSd8LgkZorLLXQfE2sEA9yz9SJt6yug8YgArWilgliv1aIzc3TOInoX6mD/jZfdQRP26/9xbfof6ucmBAuyMxL2/REgHsebp8xtqfTUnjtQo8isCqBcX3tvB1wnQtXH9dqsMPp/ibGgoHxTJXBIc5AeqV2RPlz4RMhiWuZ95dTnaOlQf3I5u8JkY40Hmied6IuB6IU4Pw7WDMnMo2fwGLNBw/fM2BgdEK3pckGEL5Yqu7UNpB+F7STVxEGIebRlAqW62IWxLuJJ4Ip6tEANFhC2NQmrNyMNHZrwFOfpf9UzjM5o36YIMfUZx/aHjRmId9myBVz3p7rxn29n+huhYn7iU=
  bucket:
    secure: vEx+UNpEXoigHbqC/6TyU9nr1noEP+R69kzzSQpH7KOpatlWtWEyG/lFDd702LJaXNWTHgz/JSOw20Ja6uIQ1yOZESrdW4bNCE26JSaNiq+MaEWLx1lyCb8IrL5YND2slnhJnz73kuWGuTyRbPozoAcJblGiTDtRVc6qHRPjY26SZNhkZzqr22R3Tf6rY7DSMlZ/QP0Srwek69KAHxJCqBd1gDhn96cPY0sEq8+ERpOsRmdzTgMRKsV/VPucVnY0gYyrKN+sUZYoCOU/MmaVJ3h88yN5e3q2utF1DulHGtwfZ2ru3oJZTU/Tsr6ZAWH43fkqTdv7hmdkOp856PABLwab+2ICMGqBt18KHGjJ3qpSjz9oQAvtK1oxYEqWTJls2GCnkF98DIY474nPWAj5EojKqcm4uOZk0KGiC4hQQASNl0VA4oFKjf2wJebr+ujsRT5vQ33Iedo9iIPhXsu2JZhxN6FRlCZ2D5+qt3X+rX0nz968WdWb1J7SB/Q4mkUla9rbyzvlf4mCRFaO2Ky4t9Hi+EhaIgHT+uFCpPSDgkT584lvMyetxIHbYoxPL2Ng7/Pfn7Gegz4sgPmoFffS+SO6kw+x8RYDKGVuCEhURGKHyBRl/87tsA9y1oJMKXpuottsOXgI2REEe3zVbGwfBiJleujx55ePBhmKM8zVPeE=
  skip_cleanup: true
