language: ruby
rvm:
- 2.2.5

before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

before_deploy: pip install --user awscli
deploy:
  provider: script
  skip_cleanup: true
  script:
    ~/.local/bin/aws s3 sync _site s3://$BUCKET --delete
  on:
    branch: master
