#!/usr/bin/env bash
set -e # halt script on error

AWS="~/.local/bin/aws"

$AWS configure set preview.cloudfront true
$AWS s3 sync _site/ s3://$BUCKET --delete
$AWS cloudfront create-invalidation --distribution $CLOUDFRONT_DISTRIBUTION_ID --paths "*"
